<?php

class User{
	private $conn;
	private $table = 'user';
	
	public $id, $uname , $village ,$taluka ,$district, $phoneno ,$adhaarno ,$length ,$breadth ,$rate ,$totalarea ,$totalamount ,$invoiceid;
	
	public function __construct($db){
		$this->conn = $db;
	}
	
	public function read(){
		$query = 'SELECT * FROM '. $this->table ;
		// print_r($this->conn);
		$result = $this->conn->query($query);
		// $result = mysqli_query($this->conn , $query);
		return $result;
	}
	
	public function read_single(){
		$query = 'SELECT * FROM '. $this->table . ' WHERE id = ' . $this->id;
		$result = $this->conn->query($query);
		$row =  mysqli_fetch_row($result);
		
		// due to extract we dont have to call $row[id] and so on
		
		// $this->id = $row[0];                      // id is autogenerated
		$this->uname = $row[1];
		$this->village = $row[2];
		$this->taluka = $row[3];
		$this->district = $row[4];
		$this->phoneno = $row[5];
		$this->adhaarno = $row[6];
		$this->length = $row[7];
		$this->breadth = $row[8];
		$this->rate = $row[9];
		$this->totalarea = $row[10];
		$this->totalamount = $row[11];
		$this->invoiceid= $row[12];
	}
	
	public function create() {
		// Create query
		$query = " INSERT INTO `user` (`uname`, `village`, `taluka`, `district`, `phoneno`, `adhaarno`,`length`, `breadth`, `rate`, `totalarea`, `totalamount`, `invoiceid`)
			VALUES ('$this->uname' , '$this->village' , '$this->taluka' , '$this->district' , $this->phoneno , $this->adhaarno , $this->length , $this->breadth , $this->rate , $this->totalarea , $this->totalamount , $this->invoiceid) ";

		// echo $query;
		$result = $this->conn->query($query);
			
		// Execute query
		if($result === TRUE) {
			return true;
		}
	}
	
}
	?>